#!/usr/bin/env ruby

def dconf(schema, name, val)
	system "gsettings", "set", schema, name, val
end

def dconf_gnome_interface(name, val)
	dconf("org.gnome.desktop.interface", name, val)
end

dconf_gnome_interface "text-scaling-factor", "1.3"
dconf_gnome_interface "cursor-size", "32"

colors = case ARGV[0]
when "dark"
	"dark"
when "toggle"
	theme = IO.popen("gsettings get org.gnome.desktop.interface gtk-theme").read
	if theme.include? "dark"
		"light"
	else
		"dark"
	end
else
	"light"
end

case colors
when "dark"
	dconf_gnome_interface "gtk-theme", "Adwaita-red-dark"
	dconf_gnome_interface "icon-theme", "ubuntu-mono-dark"
	dconf_gnome_interface "cursor-theme", "DMZ-White"
	dconf "org.gnome.gedit.preferences.editor", "scheme", "oblivion"
else 
	dconf_gnome_interface "gtk-theme", "Adwaita-red"
	dconf_gnome_interface "icon-theme", "ubuntu-mono"
	dconf_gnome_interface "cursor-theme", "DMZ-Black"
	dconf "org.gnome.gedit.preferences.editor", "scheme", "kate"
end
